"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP = ['im2latex.py']
DATA_FILES = [  ('./assets', glob('./assets/*.*')),
                ('./save_models', glob('./save_models/test.pth')),
                ('./images', glob('./images/*.*')),
                ('./utils', glob('./utils/*.*')),
                'model.py', 'api.py']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': './assets/1024.icns',
    'plist': {
        'CFBundleName': 'Im2Latex',
        'CFBundleShortVersionString': '0.1',
        'CFBundleGetInfoString': 'Im2Latex',
        'CFBundleExecutable': 'Im2Latex',
        'CFBundleIdentifier': 'com.im2latex',
        'LSUIElement': True,
    },
    'packages': ['rumps', 'torch', 'torchvision', 'matplotlib', 'sympy', 'numpy'],
}

setup(
    app=APP,
    name='Im2Latex',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'], install_requires=['rumps', 'torch', 'torchvision', 'matplotlib', 'sympy', 'numpy']
)
